// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: masterworker.proto
#ifndef GRPC_masterworker_2eproto__INCLUDED
#define GRPC_masterworker_2eproto__INCLUDED

#include "masterworker.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace masterworker {

// The masterworker service definition.
class MasterWorker final {
 public:
  static constexpr char const* service_full_name() {
    return "masterworker.MasterWorker";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status mapReduce(::grpc::ClientContext* context, const ::masterworker::MasterQuery& request, ::masterworker::WorkerReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::WorkerReply>> AsyncmapReduce(::grpc::ClientContext* context, const ::masterworker::MasterQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::WorkerReply>>(AsyncmapReduceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::WorkerReply>> PrepareAsyncmapReduce(::grpc::ClientContext* context, const ::masterworker::MasterQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::WorkerReply>>(PrepareAsyncmapReduceRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void mapReduce(::grpc::ClientContext* context, const ::masterworker::MasterQuery* request, ::masterworker::WorkerReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void mapReduce(::grpc::ClientContext* context, const ::masterworker::MasterQuery* request, ::masterworker::WorkerReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void mapReduce(::grpc::ClientContext* context, const ::masterworker::MasterQuery* request, ::masterworker::WorkerReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::WorkerReply>* AsyncmapReduceRaw(::grpc::ClientContext* context, const ::masterworker::MasterQuery& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::masterworker::WorkerReply>* PrepareAsyncmapReduceRaw(::grpc::ClientContext* context, const ::masterworker::MasterQuery& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status mapReduce(::grpc::ClientContext* context, const ::masterworker::MasterQuery& request, ::masterworker::WorkerReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::WorkerReply>> AsyncmapReduce(::grpc::ClientContext* context, const ::masterworker::MasterQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::WorkerReply>>(AsyncmapReduceRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::WorkerReply>> PrepareAsyncmapReduce(::grpc::ClientContext* context, const ::masterworker::MasterQuery& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::masterworker::WorkerReply>>(PrepareAsyncmapReduceRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void mapReduce(::grpc::ClientContext* context, const ::masterworker::MasterQuery* request, ::masterworker::WorkerReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void mapReduce(::grpc::ClientContext* context, const ::masterworker::MasterQuery* request, ::masterworker::WorkerReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void mapReduce(::grpc::ClientContext* context, const ::masterworker::MasterQuery* request, ::masterworker::WorkerReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::masterworker::WorkerReply>* AsyncmapReduceRaw(::grpc::ClientContext* context, const ::masterworker::MasterQuery& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::masterworker::WorkerReply>* PrepareAsyncmapReduceRaw(::grpc::ClientContext* context, const ::masterworker::MasterQuery& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_mapReduce_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status mapReduce(::grpc::ServerContext* context, const ::masterworker::MasterQuery* request, ::masterworker::WorkerReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_mapReduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_mapReduce() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_mapReduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mapReduce(::grpc::ServerContext* /*context*/, const ::masterworker::MasterQuery* /*request*/, ::masterworker::WorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestmapReduce(::grpc::ServerContext* context, ::masterworker::MasterQuery* request, ::grpc::ServerAsyncResponseWriter< ::masterworker::WorkerReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_mapReduce<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_mapReduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_mapReduce() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::masterworker::MasterQuery, ::masterworker::WorkerReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::masterworker::MasterQuery* request, ::masterworker::WorkerReply* response) { return this->mapReduce(context, request, response); }));}
    void SetMessageAllocatorFor_mapReduce(
        ::grpc::experimental::MessageAllocator< ::masterworker::MasterQuery, ::masterworker::WorkerReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::masterworker::MasterQuery, ::masterworker::WorkerReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_mapReduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mapReduce(::grpc::ServerContext* /*context*/, const ::masterworker::MasterQuery* /*request*/, ::masterworker::WorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* mapReduce(
      ::grpc::CallbackServerContext* /*context*/, const ::masterworker::MasterQuery* /*request*/, ::masterworker::WorkerReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* mapReduce(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::masterworker::MasterQuery* /*request*/, ::masterworker::WorkerReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_mapReduce<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_mapReduce<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_mapReduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_mapReduce() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_mapReduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mapReduce(::grpc::ServerContext* /*context*/, const ::masterworker::MasterQuery* /*request*/, ::masterworker::WorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_mapReduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_mapReduce() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_mapReduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mapReduce(::grpc::ServerContext* /*context*/, const ::masterworker::MasterQuery* /*request*/, ::masterworker::WorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestmapReduce(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_mapReduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_mapReduce() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->mapReduce(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_mapReduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status mapReduce(::grpc::ServerContext* /*context*/, const ::masterworker::MasterQuery* /*request*/, ::masterworker::WorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* mapReduce(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* mapReduce(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_mapReduce : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_mapReduce() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::masterworker::MasterQuery, ::masterworker::WorkerReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::masterworker::MasterQuery, ::masterworker::WorkerReply>* streamer) {
                       return this->StreamedmapReduce(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_mapReduce() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status mapReduce(::grpc::ServerContext* /*context*/, const ::masterworker::MasterQuery* /*request*/, ::masterworker::WorkerReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedmapReduce(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::masterworker::MasterQuery,::masterworker::WorkerReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_mapReduce<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_mapReduce<Service > StreamedService;
};

}  // namespace masterworker


#endif  // GRPC_masterworker_2eproto__INCLUDED
