// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: masterworker.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_masterworker_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_masterworker_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3014000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3014000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_masterworker_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_masterworker_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[5]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_masterworker_2eproto;
namespace masterworker {
class MapReply;
class MapReplyDefaultTypeInternal;
extern MapReplyDefaultTypeInternal _MapReply_default_instance_;
class MapRequest;
class MapRequestDefaultTypeInternal;
extern MapRequestDefaultTypeInternal _MapRequest_default_instance_;
class ReduceReply;
class ReduceReplyDefaultTypeInternal;
extern ReduceReplyDefaultTypeInternal _ReduceReply_default_instance_;
class ReduceRequest;
class ReduceRequestDefaultTypeInternal;
extern ReduceRequestDefaultTypeInternal _ReduceRequest_default_instance_;
class ShardInfo;
class ShardInfoDefaultTypeInternal;
extern ShardInfoDefaultTypeInternal _ShardInfo_default_instance_;
}  // namespace masterworker
PROTOBUF_NAMESPACE_OPEN
template<> ::masterworker::MapReply* Arena::CreateMaybeMessage<::masterworker::MapReply>(Arena*);
template<> ::masterworker::MapRequest* Arena::CreateMaybeMessage<::masterworker::MapRequest>(Arena*);
template<> ::masterworker::ReduceReply* Arena::CreateMaybeMessage<::masterworker::ReduceReply>(Arena*);
template<> ::masterworker::ReduceRequest* Arena::CreateMaybeMessage<::masterworker::ReduceRequest>(Arena*);
template<> ::masterworker::ShardInfo* Arena::CreateMaybeMessage<::masterworker::ShardInfo>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace masterworker {

// ===================================================================

class MapReply PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:masterworker.MapReply) */ {
 public:
  inline MapReply() : MapReply(nullptr) {}
  virtual ~MapReply();

  MapReply(const MapReply& from);
  MapReply(MapReply&& from) noexcept
    : MapReply() {
    *this = ::std::move(from);
  }

  inline MapReply& operator=(const MapReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline MapReply& operator=(MapReply&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MapReply& default_instance();

  static inline const MapReply* internal_default_instance() {
    return reinterpret_cast<const MapReply*>(
               &_MapReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(MapReply& a, MapReply& b) {
    a.Swap(&b);
  }
  inline void Swap(MapReply* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MapReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MapReply* New() const final {
    return CreateMaybeMessage<MapReply>(nullptr);
  }

  MapReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MapReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MapReply& from);
  void MergeFrom(const MapReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MapReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "masterworker.MapReply";
  }
  protected:
  explicit MapReply(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_masterworker_2eproto);
    return ::descriptor_table_masterworker_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIntermediateFileLocationFieldNumber = 2,
    kStatusFieldNumber = 1,
  };
  // repeated string intermediate_file_location = 2;
  int intermediate_file_location_size() const;
  private:
  int _internal_intermediate_file_location_size() const;
  public:
  void clear_intermediate_file_location();
  const std::string& intermediate_file_location(int index) const;
  std::string* mutable_intermediate_file_location(int index);
  void set_intermediate_file_location(int index, const std::string& value);
  void set_intermediate_file_location(int index, std::string&& value);
  void set_intermediate_file_location(int index, const char* value);
  void set_intermediate_file_location(int index, const char* value, size_t size);
  std::string* add_intermediate_file_location();
  void add_intermediate_file_location(const std::string& value);
  void add_intermediate_file_location(std::string&& value);
  void add_intermediate_file_location(const char* value);
  void add_intermediate_file_location(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& intermediate_file_location() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_intermediate_file_location();
  private:
  const std::string& _internal_intermediate_file_location(int index) const;
  std::string* _internal_add_intermediate_file_location();
  public:

  // bool status = 1;
  void clear_status();
  bool status() const;
  void set_status(bool value);
  private:
  bool _internal_status() const;
  void _internal_set_status(bool value);
  public:

  // @@protoc_insertion_point(class_scope:masterworker.MapReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> intermediate_file_location_;
  bool status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_masterworker_2eproto;
};
// -------------------------------------------------------------------

class ReduceReply PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:masterworker.ReduceReply) */ {
 public:
  inline ReduceReply() : ReduceReply(nullptr) {}
  virtual ~ReduceReply();

  ReduceReply(const ReduceReply& from);
  ReduceReply(ReduceReply&& from) noexcept
    : ReduceReply() {
    *this = ::std::move(from);
  }

  inline ReduceReply& operator=(const ReduceReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReduceReply& operator=(ReduceReply&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReduceReply& default_instance();

  static inline const ReduceReply* internal_default_instance() {
    return reinterpret_cast<const ReduceReply*>(
               &_ReduceReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ReduceReply& a, ReduceReply& b) {
    a.Swap(&b);
  }
  inline void Swap(ReduceReply* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReduceReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReduceReply* New() const final {
    return CreateMaybeMessage<ReduceReply>(nullptr);
  }

  ReduceReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReduceReply>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReduceReply& from);
  void MergeFrom(const ReduceReply& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReduceReply* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "masterworker.ReduceReply";
  }
  protected:
  explicit ReduceReply(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_masterworker_2eproto);
    return ::descriptor_table_masterworker_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 1,
  };
  // bool status = 1;
  void clear_status();
  bool status() const;
  void set_status(bool value);
  private:
  bool _internal_status() const;
  void _internal_set_status(bool value);
  public:

  // @@protoc_insertion_point(class_scope:masterworker.ReduceReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  bool status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_masterworker_2eproto;
};
// -------------------------------------------------------------------

class MapRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:masterworker.MapRequest) */ {
 public:
  inline MapRequest() : MapRequest(nullptr) {}
  virtual ~MapRequest();

  MapRequest(const MapRequest& from);
  MapRequest(MapRequest&& from) noexcept
    : MapRequest() {
    *this = ::std::move(from);
  }

  inline MapRequest& operator=(const MapRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline MapRequest& operator=(MapRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const MapRequest& default_instance();

  static inline const MapRequest* internal_default_instance() {
    return reinterpret_cast<const MapRequest*>(
               &_MapRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(MapRequest& a, MapRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(MapRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(MapRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline MapRequest* New() const final {
    return CreateMaybeMessage<MapRequest>(nullptr);
  }

  MapRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<MapRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const MapRequest& from);
  void MergeFrom(const MapRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(MapRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "masterworker.MapRequest";
  }
  protected:
  explicit MapRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_masterworker_2eproto);
    return ::descriptor_table_masterworker_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShardsFieldNumber = 5,
    kUserIdFieldNumber = 3,
    kOutputDirFieldNumber = 4,
    kShardIdFieldNumber = 1,
    kNOutputFieldNumber = 2,
  };
  // repeated .masterworker.ShardInfo shards = 5;
  int shards_size() const;
  private:
  int _internal_shards_size() const;
  public:
  void clear_shards();
  ::masterworker::ShardInfo* mutable_shards(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::masterworker::ShardInfo >*
      mutable_shards();
  private:
  const ::masterworker::ShardInfo& _internal_shards(int index) const;
  ::masterworker::ShardInfo* _internal_add_shards();
  public:
  const ::masterworker::ShardInfo& shards(int index) const;
  ::masterworker::ShardInfo* add_shards();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::masterworker::ShardInfo >&
      shards() const;

  // string user_id = 3;
  void clear_user_id();
  const std::string& user_id() const;
  void set_user_id(const std::string& value);
  void set_user_id(std::string&& value);
  void set_user_id(const char* value);
  void set_user_id(const char* value, size_t size);
  std::string* mutable_user_id();
  std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // string output_dir = 4;
  void clear_output_dir();
  const std::string& output_dir() const;
  void set_output_dir(const std::string& value);
  void set_output_dir(std::string&& value);
  void set_output_dir(const char* value);
  void set_output_dir(const char* value, size_t size);
  std::string* mutable_output_dir();
  std::string* release_output_dir();
  void set_allocated_output_dir(std::string* output_dir);
  private:
  const std::string& _internal_output_dir() const;
  void _internal_set_output_dir(const std::string& value);
  std::string* _internal_mutable_output_dir();
  public:

  // uint32 shard_id = 1;
  void clear_shard_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 shard_id() const;
  void set_shard_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_shard_id() const;
  void _internal_set_shard_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 n_output = 2;
  void clear_n_output();
  ::PROTOBUF_NAMESPACE_ID::uint32 n_output() const;
  void set_n_output(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_n_output() const;
  void _internal_set_n_output(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:masterworker.MapRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::masterworker::ShardInfo > shards_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr output_dir_;
  ::PROTOBUF_NAMESPACE_ID::uint32 shard_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 n_output_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_masterworker_2eproto;
};
// -------------------------------------------------------------------

class ShardInfo PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:masterworker.ShardInfo) */ {
 public:
  inline ShardInfo() : ShardInfo(nullptr) {}
  virtual ~ShardInfo();

  ShardInfo(const ShardInfo& from);
  ShardInfo(ShardInfo&& from) noexcept
    : ShardInfo() {
    *this = ::std::move(from);
  }

  inline ShardInfo& operator=(const ShardInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShardInfo& operator=(ShardInfo&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ShardInfo& default_instance();

  static inline const ShardInfo* internal_default_instance() {
    return reinterpret_cast<const ShardInfo*>(
               &_ShardInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ShardInfo& a, ShardInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ShardInfo* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShardInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ShardInfo* New() const final {
    return CreateMaybeMessage<ShardInfo>(nullptr);
  }

  ShardInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ShardInfo>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ShardInfo& from);
  void MergeFrom(const ShardInfo& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShardInfo* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "masterworker.ShardInfo";
  }
  protected:
  explicit ShardInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_masterworker_2eproto);
    return ::descriptor_table_masterworker_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileAddrFieldNumber = 1,
    kStartOffestFieldNumber = 2,
    kEndOffsetFieldNumber = 3,
  };
  // string file_addr = 1;
  void clear_file_addr();
  const std::string& file_addr() const;
  void set_file_addr(const std::string& value);
  void set_file_addr(std::string&& value);
  void set_file_addr(const char* value);
  void set_file_addr(const char* value, size_t size);
  std::string* mutable_file_addr();
  std::string* release_file_addr();
  void set_allocated_file_addr(std::string* file_addr);
  private:
  const std::string& _internal_file_addr() const;
  void _internal_set_file_addr(const std::string& value);
  std::string* _internal_mutable_file_addr();
  public:

  // uint32 start_offest = 2;
  void clear_start_offest();
  ::PROTOBUF_NAMESPACE_ID::uint32 start_offest() const;
  void set_start_offest(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_start_offest() const;
  void _internal_set_start_offest(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 end_offset = 3;
  void clear_end_offset();
  ::PROTOBUF_NAMESPACE_ID::uint32 end_offset() const;
  void set_end_offset(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_end_offset() const;
  void _internal_set_end_offset(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:masterworker.ShardInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_addr_;
  ::PROTOBUF_NAMESPACE_ID::uint32 start_offest_;
  ::PROTOBUF_NAMESPACE_ID::uint32 end_offset_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_masterworker_2eproto;
};
// -------------------------------------------------------------------

class ReduceRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:masterworker.ReduceRequest) */ {
 public:
  inline ReduceRequest() : ReduceRequest(nullptr) {}
  virtual ~ReduceRequest();

  ReduceRequest(const ReduceRequest& from);
  ReduceRequest(ReduceRequest&& from) noexcept
    : ReduceRequest() {
    *this = ::std::move(from);
  }

  inline ReduceRequest& operator=(const ReduceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ReduceRequest& operator=(ReduceRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ReduceRequest& default_instance();

  static inline const ReduceRequest* internal_default_instance() {
    return reinterpret_cast<const ReduceRequest*>(
               &_ReduceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(ReduceRequest& a, ReduceRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(ReduceRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ReduceRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ReduceRequest* New() const final {
    return CreateMaybeMessage<ReduceRequest>(nullptr);
  }

  ReduceRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ReduceRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ReduceRequest& from);
  void MergeFrom(const ReduceRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ReduceRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "masterworker.ReduceRequest";
  }
  protected:
  explicit ReduceRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_masterworker_2eproto);
    return ::descriptor_table_masterworker_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIntermediateFileAddressFieldNumber = 3,
    kUserIdFieldNumber = 1,
    kOutputDirFieldNumber = 2,
    kReducerIdFieldNumber = 4,
  };
  // repeated string intermediate_file_address = 3;
  int intermediate_file_address_size() const;
  private:
  int _internal_intermediate_file_address_size() const;
  public:
  void clear_intermediate_file_address();
  const std::string& intermediate_file_address(int index) const;
  std::string* mutable_intermediate_file_address(int index);
  void set_intermediate_file_address(int index, const std::string& value);
  void set_intermediate_file_address(int index, std::string&& value);
  void set_intermediate_file_address(int index, const char* value);
  void set_intermediate_file_address(int index, const char* value, size_t size);
  std::string* add_intermediate_file_address();
  void add_intermediate_file_address(const std::string& value);
  void add_intermediate_file_address(std::string&& value);
  void add_intermediate_file_address(const char* value);
  void add_intermediate_file_address(const char* value, size_t size);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>& intermediate_file_address() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>* mutable_intermediate_file_address();
  private:
  const std::string& _internal_intermediate_file_address(int index) const;
  std::string* _internal_add_intermediate_file_address();
  public:

  // string user_id = 1;
  void clear_user_id();
  const std::string& user_id() const;
  void set_user_id(const std::string& value);
  void set_user_id(std::string&& value);
  void set_user_id(const char* value);
  void set_user_id(const char* value, size_t size);
  std::string* mutable_user_id();
  std::string* release_user_id();
  void set_allocated_user_id(std::string* user_id);
  private:
  const std::string& _internal_user_id() const;
  void _internal_set_user_id(const std::string& value);
  std::string* _internal_mutable_user_id();
  public:

  // string output_dir = 2;
  void clear_output_dir();
  const std::string& output_dir() const;
  void set_output_dir(const std::string& value);
  void set_output_dir(std::string&& value);
  void set_output_dir(const char* value);
  void set_output_dir(const char* value, size_t size);
  std::string* mutable_output_dir();
  std::string* release_output_dir();
  void set_allocated_output_dir(std::string* output_dir);
  private:
  const std::string& _internal_output_dir() const;
  void _internal_set_output_dir(const std::string& value);
  std::string* _internal_mutable_output_dir();
  public:

  // uint32 reducer_id = 4;
  void clear_reducer_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 reducer_id() const;
  void set_reducer_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_reducer_id() const;
  void _internal_set_reducer_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:masterworker.ReduceRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string> intermediate_file_address_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr output_dir_;
  ::PROTOBUF_NAMESPACE_ID::uint32 reducer_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_masterworker_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MapReply

// bool status = 1;
inline void MapReply::clear_status() {
  status_ = false;
}
inline bool MapReply::_internal_status() const {
  return status_;
}
inline bool MapReply::status() const {
  // @@protoc_insertion_point(field_get:masterworker.MapReply.status)
  return _internal_status();
}
inline void MapReply::_internal_set_status(bool value) {
  
  status_ = value;
}
inline void MapReply::set_status(bool value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:masterworker.MapReply.status)
}

// repeated string intermediate_file_location = 2;
inline int MapReply::_internal_intermediate_file_location_size() const {
  return intermediate_file_location_.size();
}
inline int MapReply::intermediate_file_location_size() const {
  return _internal_intermediate_file_location_size();
}
inline void MapReply::clear_intermediate_file_location() {
  intermediate_file_location_.Clear();
}
inline std::string* MapReply::add_intermediate_file_location() {
  // @@protoc_insertion_point(field_add_mutable:masterworker.MapReply.intermediate_file_location)
  return _internal_add_intermediate_file_location();
}
inline const std::string& MapReply::_internal_intermediate_file_location(int index) const {
  return intermediate_file_location_.Get(index);
}
inline const std::string& MapReply::intermediate_file_location(int index) const {
  // @@protoc_insertion_point(field_get:masterworker.MapReply.intermediate_file_location)
  return _internal_intermediate_file_location(index);
}
inline std::string* MapReply::mutable_intermediate_file_location(int index) {
  // @@protoc_insertion_point(field_mutable:masterworker.MapReply.intermediate_file_location)
  return intermediate_file_location_.Mutable(index);
}
inline void MapReply::set_intermediate_file_location(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:masterworker.MapReply.intermediate_file_location)
  intermediate_file_location_.Mutable(index)->assign(value);
}
inline void MapReply::set_intermediate_file_location(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:masterworker.MapReply.intermediate_file_location)
  intermediate_file_location_.Mutable(index)->assign(std::move(value));
}
inline void MapReply::set_intermediate_file_location(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  intermediate_file_location_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:masterworker.MapReply.intermediate_file_location)
}
inline void MapReply::set_intermediate_file_location(int index, const char* value, size_t size) {
  intermediate_file_location_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:masterworker.MapReply.intermediate_file_location)
}
inline std::string* MapReply::_internal_add_intermediate_file_location() {
  return intermediate_file_location_.Add();
}
inline void MapReply::add_intermediate_file_location(const std::string& value) {
  intermediate_file_location_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:masterworker.MapReply.intermediate_file_location)
}
inline void MapReply::add_intermediate_file_location(std::string&& value) {
  intermediate_file_location_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:masterworker.MapReply.intermediate_file_location)
}
inline void MapReply::add_intermediate_file_location(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  intermediate_file_location_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:masterworker.MapReply.intermediate_file_location)
}
inline void MapReply::add_intermediate_file_location(const char* value, size_t size) {
  intermediate_file_location_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:masterworker.MapReply.intermediate_file_location)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
MapReply::intermediate_file_location() const {
  // @@protoc_insertion_point(field_list:masterworker.MapReply.intermediate_file_location)
  return intermediate_file_location_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
MapReply::mutable_intermediate_file_location() {
  // @@protoc_insertion_point(field_mutable_list:masterworker.MapReply.intermediate_file_location)
  return &intermediate_file_location_;
}

// -------------------------------------------------------------------

// ReduceReply

// bool status = 1;
inline void ReduceReply::clear_status() {
  status_ = false;
}
inline bool ReduceReply::_internal_status() const {
  return status_;
}
inline bool ReduceReply::status() const {
  // @@protoc_insertion_point(field_get:masterworker.ReduceReply.status)
  return _internal_status();
}
inline void ReduceReply::_internal_set_status(bool value) {
  
  status_ = value;
}
inline void ReduceReply::set_status(bool value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:masterworker.ReduceReply.status)
}

// -------------------------------------------------------------------

// MapRequest

// uint32 shard_id = 1;
inline void MapRequest::clear_shard_id() {
  shard_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MapRequest::_internal_shard_id() const {
  return shard_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MapRequest::shard_id() const {
  // @@protoc_insertion_point(field_get:masterworker.MapRequest.shard_id)
  return _internal_shard_id();
}
inline void MapRequest::_internal_set_shard_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  shard_id_ = value;
}
inline void MapRequest::set_shard_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_shard_id(value);
  // @@protoc_insertion_point(field_set:masterworker.MapRequest.shard_id)
}

// uint32 n_output = 2;
inline void MapRequest::clear_n_output() {
  n_output_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MapRequest::_internal_n_output() const {
  return n_output_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 MapRequest::n_output() const {
  // @@protoc_insertion_point(field_get:masterworker.MapRequest.n_output)
  return _internal_n_output();
}
inline void MapRequest::_internal_set_n_output(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  n_output_ = value;
}
inline void MapRequest::set_n_output(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_n_output(value);
  // @@protoc_insertion_point(field_set:masterworker.MapRequest.n_output)
}

// string user_id = 3;
inline void MapRequest::clear_user_id() {
  user_id_.ClearToEmpty();
}
inline const std::string& MapRequest::user_id() const {
  // @@protoc_insertion_point(field_get:masterworker.MapRequest.user_id)
  return _internal_user_id();
}
inline void MapRequest::set_user_id(const std::string& value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:masterworker.MapRequest.user_id)
}
inline std::string* MapRequest::mutable_user_id() {
  // @@protoc_insertion_point(field_mutable:masterworker.MapRequest.user_id)
  return _internal_mutable_user_id();
}
inline const std::string& MapRequest::_internal_user_id() const {
  return user_id_.Get();
}
inline void MapRequest::_internal_set_user_id(const std::string& value) {
  
  user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void MapRequest::set_user_id(std::string&& value) {
  
  user_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:masterworker.MapRequest.user_id)
}
inline void MapRequest::set_user_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:masterworker.MapRequest.user_id)
}
inline void MapRequest::set_user_id(const char* value,
    size_t size) {
  
  user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:masterworker.MapRequest.user_id)
}
inline std::string* MapRequest::_internal_mutable_user_id() {
  
  return user_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* MapRequest::release_user_id() {
  // @@protoc_insertion_point(field_release:masterworker.MapRequest.user_id)
  return user_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MapRequest::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {
    
  } else {
    
  }
  user_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:masterworker.MapRequest.user_id)
}

// string output_dir = 4;
inline void MapRequest::clear_output_dir() {
  output_dir_.ClearToEmpty();
}
inline const std::string& MapRequest::output_dir() const {
  // @@protoc_insertion_point(field_get:masterworker.MapRequest.output_dir)
  return _internal_output_dir();
}
inline void MapRequest::set_output_dir(const std::string& value) {
  _internal_set_output_dir(value);
  // @@protoc_insertion_point(field_set:masterworker.MapRequest.output_dir)
}
inline std::string* MapRequest::mutable_output_dir() {
  // @@protoc_insertion_point(field_mutable:masterworker.MapRequest.output_dir)
  return _internal_mutable_output_dir();
}
inline const std::string& MapRequest::_internal_output_dir() const {
  return output_dir_.Get();
}
inline void MapRequest::_internal_set_output_dir(const std::string& value) {
  
  output_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void MapRequest::set_output_dir(std::string&& value) {
  
  output_dir_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:masterworker.MapRequest.output_dir)
}
inline void MapRequest::set_output_dir(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  output_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:masterworker.MapRequest.output_dir)
}
inline void MapRequest::set_output_dir(const char* value,
    size_t size) {
  
  output_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:masterworker.MapRequest.output_dir)
}
inline std::string* MapRequest::_internal_mutable_output_dir() {
  
  return output_dir_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* MapRequest::release_output_dir() {
  // @@protoc_insertion_point(field_release:masterworker.MapRequest.output_dir)
  return output_dir_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void MapRequest::set_allocated_output_dir(std::string* output_dir) {
  if (output_dir != nullptr) {
    
  } else {
    
  }
  output_dir_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), output_dir,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:masterworker.MapRequest.output_dir)
}

// repeated .masterworker.ShardInfo shards = 5;
inline int MapRequest::_internal_shards_size() const {
  return shards_.size();
}
inline int MapRequest::shards_size() const {
  return _internal_shards_size();
}
inline void MapRequest::clear_shards() {
  shards_.Clear();
}
inline ::masterworker::ShardInfo* MapRequest::mutable_shards(int index) {
  // @@protoc_insertion_point(field_mutable:masterworker.MapRequest.shards)
  return shards_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::masterworker::ShardInfo >*
MapRequest::mutable_shards() {
  // @@protoc_insertion_point(field_mutable_list:masterworker.MapRequest.shards)
  return &shards_;
}
inline const ::masterworker::ShardInfo& MapRequest::_internal_shards(int index) const {
  return shards_.Get(index);
}
inline const ::masterworker::ShardInfo& MapRequest::shards(int index) const {
  // @@protoc_insertion_point(field_get:masterworker.MapRequest.shards)
  return _internal_shards(index);
}
inline ::masterworker::ShardInfo* MapRequest::_internal_add_shards() {
  return shards_.Add();
}
inline ::masterworker::ShardInfo* MapRequest::add_shards() {
  // @@protoc_insertion_point(field_add:masterworker.MapRequest.shards)
  return _internal_add_shards();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::masterworker::ShardInfo >&
MapRequest::shards() const {
  // @@protoc_insertion_point(field_list:masterworker.MapRequest.shards)
  return shards_;
}

// -------------------------------------------------------------------

// ShardInfo

// string file_addr = 1;
inline void ShardInfo::clear_file_addr() {
  file_addr_.ClearToEmpty();
}
inline const std::string& ShardInfo::file_addr() const {
  // @@protoc_insertion_point(field_get:masterworker.ShardInfo.file_addr)
  return _internal_file_addr();
}
inline void ShardInfo::set_file_addr(const std::string& value) {
  _internal_set_file_addr(value);
  // @@protoc_insertion_point(field_set:masterworker.ShardInfo.file_addr)
}
inline std::string* ShardInfo::mutable_file_addr() {
  // @@protoc_insertion_point(field_mutable:masterworker.ShardInfo.file_addr)
  return _internal_mutable_file_addr();
}
inline const std::string& ShardInfo::_internal_file_addr() const {
  return file_addr_.Get();
}
inline void ShardInfo::_internal_set_file_addr(const std::string& value) {
  
  file_addr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ShardInfo::set_file_addr(std::string&& value) {
  
  file_addr_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:masterworker.ShardInfo.file_addr)
}
inline void ShardInfo::set_file_addr(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  file_addr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:masterworker.ShardInfo.file_addr)
}
inline void ShardInfo::set_file_addr(const char* value,
    size_t size) {
  
  file_addr_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:masterworker.ShardInfo.file_addr)
}
inline std::string* ShardInfo::_internal_mutable_file_addr() {
  
  return file_addr_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ShardInfo::release_file_addr() {
  // @@protoc_insertion_point(field_release:masterworker.ShardInfo.file_addr)
  return file_addr_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ShardInfo::set_allocated_file_addr(std::string* file_addr) {
  if (file_addr != nullptr) {
    
  } else {
    
  }
  file_addr_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), file_addr,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:masterworker.ShardInfo.file_addr)
}

// uint32 start_offest = 2;
inline void ShardInfo::clear_start_offest() {
  start_offest_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ShardInfo::_internal_start_offest() const {
  return start_offest_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ShardInfo::start_offest() const {
  // @@protoc_insertion_point(field_get:masterworker.ShardInfo.start_offest)
  return _internal_start_offest();
}
inline void ShardInfo::_internal_set_start_offest(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  start_offest_ = value;
}
inline void ShardInfo::set_start_offest(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_start_offest(value);
  // @@protoc_insertion_point(field_set:masterworker.ShardInfo.start_offest)
}

// uint32 end_offset = 3;
inline void ShardInfo::clear_end_offset() {
  end_offset_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ShardInfo::_internal_end_offset() const {
  return end_offset_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ShardInfo::end_offset() const {
  // @@protoc_insertion_point(field_get:masterworker.ShardInfo.end_offset)
  return _internal_end_offset();
}
inline void ShardInfo::_internal_set_end_offset(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  end_offset_ = value;
}
inline void ShardInfo::set_end_offset(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_end_offset(value);
  // @@protoc_insertion_point(field_set:masterworker.ShardInfo.end_offset)
}

// -------------------------------------------------------------------

// ReduceRequest

// string user_id = 1;
inline void ReduceRequest::clear_user_id() {
  user_id_.ClearToEmpty();
}
inline const std::string& ReduceRequest::user_id() const {
  // @@protoc_insertion_point(field_get:masterworker.ReduceRequest.user_id)
  return _internal_user_id();
}
inline void ReduceRequest::set_user_id(const std::string& value) {
  _internal_set_user_id(value);
  // @@protoc_insertion_point(field_set:masterworker.ReduceRequest.user_id)
}
inline std::string* ReduceRequest::mutable_user_id() {
  // @@protoc_insertion_point(field_mutable:masterworker.ReduceRequest.user_id)
  return _internal_mutable_user_id();
}
inline const std::string& ReduceRequest::_internal_user_id() const {
  return user_id_.Get();
}
inline void ReduceRequest::_internal_set_user_id(const std::string& value) {
  
  user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ReduceRequest::set_user_id(std::string&& value) {
  
  user_id_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:masterworker.ReduceRequest.user_id)
}
inline void ReduceRequest::set_user_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:masterworker.ReduceRequest.user_id)
}
inline void ReduceRequest::set_user_id(const char* value,
    size_t size) {
  
  user_id_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:masterworker.ReduceRequest.user_id)
}
inline std::string* ReduceRequest::_internal_mutable_user_id() {
  
  return user_id_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ReduceRequest::release_user_id() {
  // @@protoc_insertion_point(field_release:masterworker.ReduceRequest.user_id)
  return user_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ReduceRequest::set_allocated_user_id(std::string* user_id) {
  if (user_id != nullptr) {
    
  } else {
    
  }
  user_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), user_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:masterworker.ReduceRequest.user_id)
}

// string output_dir = 2;
inline void ReduceRequest::clear_output_dir() {
  output_dir_.ClearToEmpty();
}
inline const std::string& ReduceRequest::output_dir() const {
  // @@protoc_insertion_point(field_get:masterworker.ReduceRequest.output_dir)
  return _internal_output_dir();
}
inline void ReduceRequest::set_output_dir(const std::string& value) {
  _internal_set_output_dir(value);
  // @@protoc_insertion_point(field_set:masterworker.ReduceRequest.output_dir)
}
inline std::string* ReduceRequest::mutable_output_dir() {
  // @@protoc_insertion_point(field_mutable:masterworker.ReduceRequest.output_dir)
  return _internal_mutable_output_dir();
}
inline const std::string& ReduceRequest::_internal_output_dir() const {
  return output_dir_.Get();
}
inline void ReduceRequest::_internal_set_output_dir(const std::string& value) {
  
  output_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArena());
}
inline void ReduceRequest::set_output_dir(std::string&& value) {
  
  output_dir_.Set(
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:masterworker.ReduceRequest.output_dir)
}
inline void ReduceRequest::set_output_dir(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  output_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(value), GetArena());
  // @@protoc_insertion_point(field_set_char:masterworker.ReduceRequest.output_dir)
}
inline void ReduceRequest::set_output_dir(const char* value,
    size_t size) {
  
  output_dir_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:masterworker.ReduceRequest.output_dir)
}
inline std::string* ReduceRequest::_internal_mutable_output_dir() {
  
  return output_dir_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
}
inline std::string* ReduceRequest::release_output_dir() {
  // @@protoc_insertion_point(field_release:masterworker.ReduceRequest.output_dir)
  return output_dir_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void ReduceRequest::set_allocated_output_dir(std::string* output_dir) {
  if (output_dir != nullptr) {
    
  } else {
    
  }
  output_dir_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), output_dir,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:masterworker.ReduceRequest.output_dir)
}

// repeated string intermediate_file_address = 3;
inline int ReduceRequest::_internal_intermediate_file_address_size() const {
  return intermediate_file_address_.size();
}
inline int ReduceRequest::intermediate_file_address_size() const {
  return _internal_intermediate_file_address_size();
}
inline void ReduceRequest::clear_intermediate_file_address() {
  intermediate_file_address_.Clear();
}
inline std::string* ReduceRequest::add_intermediate_file_address() {
  // @@protoc_insertion_point(field_add_mutable:masterworker.ReduceRequest.intermediate_file_address)
  return _internal_add_intermediate_file_address();
}
inline const std::string& ReduceRequest::_internal_intermediate_file_address(int index) const {
  return intermediate_file_address_.Get(index);
}
inline const std::string& ReduceRequest::intermediate_file_address(int index) const {
  // @@protoc_insertion_point(field_get:masterworker.ReduceRequest.intermediate_file_address)
  return _internal_intermediate_file_address(index);
}
inline std::string* ReduceRequest::mutable_intermediate_file_address(int index) {
  // @@protoc_insertion_point(field_mutable:masterworker.ReduceRequest.intermediate_file_address)
  return intermediate_file_address_.Mutable(index);
}
inline void ReduceRequest::set_intermediate_file_address(int index, const std::string& value) {
  // @@protoc_insertion_point(field_set:masterworker.ReduceRequest.intermediate_file_address)
  intermediate_file_address_.Mutable(index)->assign(value);
}
inline void ReduceRequest::set_intermediate_file_address(int index, std::string&& value) {
  // @@protoc_insertion_point(field_set:masterworker.ReduceRequest.intermediate_file_address)
  intermediate_file_address_.Mutable(index)->assign(std::move(value));
}
inline void ReduceRequest::set_intermediate_file_address(int index, const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  intermediate_file_address_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:masterworker.ReduceRequest.intermediate_file_address)
}
inline void ReduceRequest::set_intermediate_file_address(int index, const char* value, size_t size) {
  intermediate_file_address_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:masterworker.ReduceRequest.intermediate_file_address)
}
inline std::string* ReduceRequest::_internal_add_intermediate_file_address() {
  return intermediate_file_address_.Add();
}
inline void ReduceRequest::add_intermediate_file_address(const std::string& value) {
  intermediate_file_address_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:masterworker.ReduceRequest.intermediate_file_address)
}
inline void ReduceRequest::add_intermediate_file_address(std::string&& value) {
  intermediate_file_address_.Add(std::move(value));
  // @@protoc_insertion_point(field_add:masterworker.ReduceRequest.intermediate_file_address)
}
inline void ReduceRequest::add_intermediate_file_address(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  intermediate_file_address_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:masterworker.ReduceRequest.intermediate_file_address)
}
inline void ReduceRequest::add_intermediate_file_address(const char* value, size_t size) {
  intermediate_file_address_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:masterworker.ReduceRequest.intermediate_file_address)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>&
ReduceRequest::intermediate_file_address() const {
  // @@protoc_insertion_point(field_list:masterworker.ReduceRequest.intermediate_file_address)
  return intermediate_file_address_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField<std::string>*
ReduceRequest::mutable_intermediate_file_address() {
  // @@protoc_insertion_point(field_mutable_list:masterworker.ReduceRequest.intermediate_file_address)
  return &intermediate_file_address_;
}

// uint32 reducer_id = 4;
inline void ReduceRequest::clear_reducer_id() {
  reducer_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ReduceRequest::_internal_reducer_id() const {
  return reducer_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 ReduceRequest::reducer_id() const {
  // @@protoc_insertion_point(field_get:masterworker.ReduceRequest.reducer_id)
  return _internal_reducer_id();
}
inline void ReduceRequest::_internal_set_reducer_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  reducer_id_ = value;
}
inline void ReduceRequest::set_reducer_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_reducer_id(value);
  // @@protoc_insertion_point(field_set:masterworker.ReduceRequest.reducer_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace masterworker

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_masterworker_2eproto
